### ISSUE TITLE
numpy vs np

### ISSUE THREAD

**Issue by anelles** [icecube/toise#45]
Maybe this is some python magic unknown to me, but how did pointsource.py ever work with 
`import numpy`
and then using e.g.
`np.loadtxt(path.join(data_dir,...`
Maybe someone can enlighten me ... but I guess it never needed to work standalone. 

However, at least for coherence sake, I would suggest that we either use `numpy` or `np` throughout the code. Rather than having to add a random `import numpy as np` everywhere.

**Comment by shallmann** [comment]
I guess it never needed to work standalone... unless @jvansanten has a strong preference for `numpy` vs `np` I replaced all occurences by `np` in the 45-numpy-vs-np branch. Will make a PR on this.

**Comment by jvansanten** [comment]
Fixed by #58
